#
# TODO: add description & license header
#
name: Code Format & PlatformIO Build
on: [push]
jobs:
  format:
    name: Clang-Format
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: sudo apt-get install -y clang-format
      - name: checkout
        uses: actions/checkout@v2
      - name: format
        run: find . -not -path "./.*" -name "*.cpp" -o -name "*.c" -o -name "*.h" | xargs -I {} clang-format -i {}
      - name: diff
        run: git diff --exit-code
  build:
    name: PlatformIO CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.pio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Run PlatformIO
        run: pio run
