#
# TODO: add description & license header
#
name: File Formatting Process
on:
  pull_request:
    branches: [master]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actionsx/prettier@v2
        with:
          args: --write .
      - name: install clang-format
        run: |
          sudo apt-get install clang-format
      - name: run clang-format
        run: find . -name "*.cpp" -o -name "*.c" -o -name "*.h"|xargs -I {} clang-format -i {}
      - name: commit changes & push
        run: |
          git config --global user.email "formatter@bot"
          git config --global user.name "Formatter Bot"
          if [ -n "$(git status --porcelain)" ]; then
            git commit . -m "Apply clang-format" &&
            git push origin
          fi
          
