name: Format
on:
  pull_request:
    branches: [master]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actionsx/prettier@v2
        with:
          args: --write .
          
      - uses: actions/checkout@v2
      - name: Run clang-format
        uses: HorstBaerbel/action-clang-format@1.4
        with:
          scandir: '.'
          excludedirs: 'build'
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
          style: 'file'
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
